version: "3.9"

services:
  db:
    image: "mysql:${MYSQL_VERSION}"
    restart: always
    environment:
      MYSQL_DATABASE: "${MYSQL_DB}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - mysqldb-vol:/var/lib/mysql

volumes:
  mysqldb-vol:
